#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# setup_secrets.sh — inject secrets into source files
#
# Usage:
#   bash scripts/setup_secrets.sh
#
# Requires: secrets.env in the project root (copy from secrets.env.example)
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# ── 1. Load secrets ───────────────────────────────────────────────────────────
SECRETS_FILE="$ROOT/secrets.env"
if [ ! -f "$SECRETS_FILE" ]; then
  echo "❌  secrets.env not found."
  echo "    Copy the template and fill in your values:"
  echo "      cp secrets.env.example secrets.env"
  exit 1
fi

# shellcheck source=/dev/null
set -o allexport
source "$SECRETS_FILE"
set +o allexport

REQUIRED=(
  GOOGLE_SERVER_CLIENT_ID
  GOOGLE_IOS_CLIENT_ID
  GOOGLE_REVERSED_CLIENT_ID
  BUNDLE_ID
  APP_GROUP_ID
)
for VAR in "${REQUIRED[@]}"; do
  if [ -z "${!VAR:-}" ] || [[ "${!VAR}" == YOUR_* ]]; then
    echo "❌  $VAR is not set in secrets.env"
    exit 1
  fi
done

# ── 2. Generate lib/core/config/app_secrets.dart ──────────────────────────────
DART_OUT="$ROOT/lib/core/config/app_secrets.dart"
cat > "$DART_OUT" <<DART
// Auto-generated by scripts/setup_secrets.sh — DO NOT COMMIT
class AppSecrets {
  static const googleServerClientId  = '$GOOGLE_SERVER_CLIENT_ID';
  static const googleIosClientId     = '$GOOGLE_IOS_CLIENT_ID';
  static const googleReversedClientId = '$GOOGLE_REVERSED_CLIENT_ID';
  static const bundleId   = '$BUNDLE_ID';
  static const appGroupId = '$APP_GROUP_ID';
}
DART
echo "✅  lib/core/config/app_secrets.dart"

# ── 3. Generate ios/Runner/GoogleService-Info.plist ───────────────────────────
PLIST_TEMPLATE="$ROOT/ios/Runner/GoogleService-Info.plist.template"
PLIST_OUT="$ROOT/ios/Runner/GoogleService-Info.plist"
sed \
  -e "s|__GOOGLE_IOS_CLIENT_ID__|$GOOGLE_IOS_CLIENT_ID|g" \
  -e "s|__GOOGLE_REVERSED_CLIENT_ID__|$GOOGLE_REVERSED_CLIENT_ID|g" \
  -e "s|__BUNDLE_ID__|$BUNDLE_ID|g" \
  "$PLIST_TEMPLATE" > "$PLIST_OUT"
echo "✅  ios/Runner/GoogleService-Info.plist"

# ── 4. Patch ios/Runner/Info.plist (Google Sign-In URL scheme) ────────────────
# Info.plist is tracked in git with a placeholder (__GOOGLE_REVERSED_CLIENT_ID__)
# We substitute it in-place and mark the file as skip-worktree so git ignores
# the local change.
INFO_PLIST="$ROOT/ios/Runner/Info.plist"
# Make sure skip-worktree is off so we can write
git -C "$ROOT" update-index --no-skip-worktree "$INFO_PLIST" 2>/dev/null || true
# Substitute placeholder (idempotent: only acts if placeholder is present)
if grep -q "__GOOGLE_REVERSED_CLIENT_ID__" "$INFO_PLIST"; then
  sed -i '' \
    "s|__GOOGLE_REVERSED_CLIENT_ID__|$GOOGLE_REVERSED_CLIENT_ID|g" \
    "$INFO_PLIST"
fi
# Tell git to ignore local changes to this file from now on
git -C "$ROOT" update-index --skip-worktree "$INFO_PLIST" 2>/dev/null || true
echo "✅  ios/Runner/Info.plist  (git skip-worktree set)"

echo ""
echo "🎉  All secrets injected. You're ready to build."
